/**
 * Get an array with a specified length, filled with indices
 * @param length Length of the array
 * @returns Array of indices
 */
export function range(length: number): number[];

/**
 * Get an array of numbers in a specified range
 * @param start Starting number _(inclusive)_
 * @param end Ending number _(exclusive)_
 * @returns Array of numbers in range
 */
export function range(start: number, end: number): number[];

/**
 * Get an array of numbers in a specified range with a specified step
 * @param start Starting number _(inclusive)_
 * @param end Ending number _(exclusive)_
 * @param step Step between numbers
 * @returns Array of numbers in range
 */
export function range(start: number, end: number, step: number): number[];

export function range(first: number, second?: number, third?: number): number[] {
	const start = typeof second === 'number' ? first : 0;
	const end = typeof second === 'number' ? second : first;
	const step = typeof third === 'number' ? third : 1;

	const values: number[] = [];

	if (step === 0) {
		return values;
	}

	if (step > 0) {
		for (let i = start; i < end; i += step) {
			values.push(i);
		}
	} else {
		for (let i = start; i > end; i += step) {
			values.push(i);
		}
	}

	return values;
}

/**
 * Get an array with a specified length, filled with indices
 * @param length Length of the array
 * @returns Array of indices
 */
export function times(length: number): number[];

/**
 * Get an array with a specified length, filled by values from a callback
 * @param length Length of the array
 * @param callback Callback function to generate values
 * @returns Array of values generated by the callback
 */
export function times<Callback extends (index: number) => unknown>(
	length: number,
	callback: Callback,
): ReturnType<Callback>[];

/**
 * Get an array with a specified length, filled with a specified value
 * @param length Length of the array
 * @param value Value to fill the array with
 * @returns Array filled with the specified value
 */
export function times<Value>(length: number, value: Value): Value[];

export function times(length: number, value?: unknown): unknown[] {
	if (typeof length !== 'number' || length <= 0) {
		return [];
	}

	const isFunction = typeof value === 'function';

	const values: unknown[] = [];

	for (let index = 0; index < length; index += 1) {
		values.push(isFunction ? (value as (index: number) => unknown)(index) : (value ?? index));
	}

	return values;
}
