/**
 * Get an array with a specified length, filled with indices
 * @param length Length of the array
 * @return Arry of indices
 */
export function range(length: number): number[];

/**
 * Get an array with a specified length, filled by values from a callback
 * @param length Length of the array
 * @param callback Callback function to generate values
 * @return Array of values generated by the callback
 */
export function range<Callback extends (index: number) => unknown>(
	length: number,
	callback: Callback,
): ReturnType<Callback>[];

/**
 * Get an array with a specified length, filled with a specified value
 * @param length Length of the array
 * @param value Value to fill the array with
 * @return Array filled with the specified value
 */
export function range<Value>(length: number, value: Value): Value[];

export function range(length: number, value?: unknown): unknown[] {
	if (typeof length !== 'number' || length <= 0) {
		return [];
	}

	const isFunction = typeof value === 'function';

	return Array.from({length}, (_, index) => (isFunction ? value(index) : (value ?? index)));
}
