export {compare} from '../internal/value/compare';
export {diff} from './diff';
export {equal} from '../internal/value/equal';
export {getValue} from '../internal/value/get';
export {setValue} from '../internal/value/set';
export type {ArrayOrPlainObject, NestedPartial, PlainObject} from '../models';
export {clone} from './clone';
export {merge} from './merge';
export {partial} from './partial';
export {smush} from './smush';
export {unsmush} from './unsmush';
